{
  "nodes":[
    {"name":"asd","group":1},
    {"name":"zxc","group":2},
    {"name":"qwe","group":3}
  ],
  "links":[
    {"source":1,"target":0,"value":1},
    {"source":1,"target":2,"value":1},
     {"source":2,"target":0,"value":1}
  ]
}